### ISSUE TITLE
Would like to contribute

### ISSUE THREAD

**Issue by peoray** [Orlandster/vue-page-transition#14]
Hi, I'd love to contribute to this project. What do I need to know?
Great work btw :)

**Comment by Orlandster** [comment]
@peoray Hey, this sounds awesome!
Basically there is not too much stuff to know. All the transitions are made with Vue.js transition feature: https://vuejs.org/v2/guide/transitions.html

You can find all the transitions located in the `src/transitions` folder:
https://github.com/Orlandster/vue-page-transition/tree/master/src/styles

So can simply add them. In addition they are group in child transitions. (e.g. `/fade`)

Finally to make it work you would need to include the transition in the entry component:
https://github.com/Orlandster/vue-page-transition/blob/master/src/components/VuePageTransition.vue

**Comment by peoray** [comment]
Great, I'll get started as soon as I can
