### ISSUE TITLE
Does not work in IE 11.

### ISSUE THREAD

**Issue by myoneflag** [Orlandster/vue-page-transition#26]
I have integrated this package in my simple project. For chrome, works well. but does not work in IE 11. I have got following error.
`SCRIPT1003**: Excepted ':'**
vue-page-transition.common.js (91, 1)`
Please help me. Regards

**Comment by zifnab87** [comment]
any updates on this? it seems that the module isnt built so that functions are like that:
```
{ func: function() {} }
```
instead of
```
{ func() {} }
```

**Comment by Sheens1983** [comment]
Just had the same issue! Is there any resolution on this?

**Comment by zifnab87** [comment]
> Just had the same issue! Is there any resolution on this?

We had to rely on built-in vue page transition because it was breaking our whole project in IE11. So we removed it unfortunately

**Comment by myoneflag** [comment]
Me too, Just removed

**Comment by JackEdwardLyons** [comment]
Same issue for me too, any news on this?

**Comment by ontwikkelfabriek** [comment]
why is this closed? It's broken on ie11.

**Comment by matteocacciola** [comment]
If you still need something working on IE11, please use this fork https://github.com/matteocacciola/vue-page-transition
